import socket

UDP_IP = "140.252.33.33"
UDP_PORT = 54321
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(100)

MESSAGE = "ADDR,3,0;"

def write(msg):
    sock.sendto(msg, (UDP_IP, UDP_PORT))
    for i in range(10):
        data, addr = sock.recvfrom(1024)
        print "%s -> %s" % (msg, data)
        if data == "OK;" or data == "ERROR;":
            break

write("ADDR,2,1;")
write("FUNC,3,1;")
write("GLOBAL,3,3,4,5;")
write("SEND_FIFO;")
            
#write("SEND_ADDR,1;")
#write("ADDR,1,1;")
#write("SEND_ADDR,1;")
#write("SEND_FUNC,1;")
#write("FUNC,1,1;")
#write("SEND_FUNC,1;")
#write("RESET;")
#write("SEND_ADDR,1;")
#write("SEND_FUNC,1;")
#write("SEND_FIFO;")
#write("ADD_FIFO,1,3,2,4;")
#write("ADD_FIFO,9,7,10,22;")
#write("SEND_FIFO;")
#write("SEND_GLOBAL,3;")
#write("GLOBAL,3,1,2,3;")
#write("SEND_GLOBAL,3;")
#write("GLOBAL,3;")
#write("SEND_GLOBAL,3;")
#write("GLOBAL,3,5,8,2,3;")
#write("SEND_GLOBAL,3;")
#write("RESET;")
#write("SEND_GLOBAL,3;")
#write("SEND_UNIQUE,3,4;")
#write("UNIQUE,3,4,1,2,3;")
#write("SEND_UNIQUE,3,4;")
#write("SEND_UNIQUE,3,4;")
#write("UNIQUE,3,4;")
#write("SEND_UNIQUE,3,4;")
#write("UNIQUE,3,4,1,2,3;")
#write("SEND_UNIQUE,3,4;")
#write("RESET;")
#write("SEND_UNIQUE,3,4;")
#write("SEND_MODE,3,4;")
#write("UNIQUE,3,4,5,4,3;")
#write("SEND_MODE,3,4;")
#write("RESET;")
#write("ADDR,3,1;")
#write("ADDR,2,1;")
#write("ADDR,1,1;")
#write("FUNC,4,1;")
#write("FUNC,2,1;")
#write("ADDR,4,1;")
#write("GLOBAL,4,10,11,12;")
#write("SIMULATE,3,4;")
#write("UNIQUE,3,4,1,2,3;")
#write("SIMULATE,3,4;")
#write("SIMULATE,2,4;")
#write("UNIQUE,1,4,2,255,255;")
#write("SIMULATE,1,4;")
#write("SIMULATE,4,3;")
#write("UNIQUE,4,2,9,7,5,6,4;")
#write("SIMULATE,4,2;")